<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>HocLieu.QuizImport</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="DocumentFormat.OpenXml" />
  </ItemGroup>

</Project>
