// <auto-generated />
using System;
using HocLieu.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HocLieu.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HocLieu.Domain.Entities.Announcement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("audience");

                    b.Property<string>("BodyHtml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_html");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("ExpireAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expire_at");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pinned");

                    b.Property<DateTimeOffset?>("PublishAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publish_at");

                    b.Property<long?>("TeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("team_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_announcements");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_announcements_team_id");

                    b.HasIndex("Audience", "PublishAt")
                        .HasDatabaseName("ix_announcements_audience_publish_at");

                    b.ToTable("announcements", (string)null);
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_app_settings");

                    b.ToTable("app_settings", (string)null);
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.Assignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<DateTimeOffset?>("CloseAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("close_at");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character(6)")
                        .HasColumnName("code")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("OpenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("open_at");

                    b.Property<long>("QuizId")
                        .HasColumnType("bigint")
                        .HasColumnName("quiz_id");

                    b.Property<bool>("UseRoster")
                        .HasColumnType("boolean")
                        .HasColumnName("use_roster");

                    b.HasKey("Id")
                        .HasName("pk_assignments");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_assignments_class_id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_assignments_code");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_assignments_created_by");

                    b.HasIndex("QuizId")
                        .HasDatabaseName("ix_assignments_quiz_id");

                    b.ToTable("assignments", (string)null);
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.Attempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("AssignmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("assignment_id");

                    b.Property<int?>("CorrectCount")
                        .HasColumnType("integer")
                        .HasColumnName("correct_count");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<int?>("DurationSec")
                        .HasColumnType("integer")
                        .HasColumnName("duration_sec");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("GuestClass")
                        .HasColumnType("text")
                        .HasColumnName("guest_class");

                    b.Property<string>("GuestName")
                        .HasColumnType("text")
                        .HasColumnName("guest_name");

                    b.Property<string>("IpHash")
                        .HasColumnType("text")
                        .HasColumnName("ip_hash");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("layout");

                    b.Property<int?>("QuestionCount")
                        .HasColumnType("integer")
                        .HasColumnName("question_count");

                    b.Property<long>("QuizId")
                        .HasColumnType("bigint")
                        .HasColumnName("quiz_id");

                    b.Property<decimal?>("Score")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("score");

                    b.Property<decimal?>("Score10")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("score_10");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<long?>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("student_id");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.HasKey("Id")
                        .HasName("pk_attempts");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_attempts_student_id");

                    b.HasIndex("AssignmentId", "StudentId")
                        .HasDatabaseName("ix_attempts_assignment_id_student_id");

                    b.HasIndex("QuizId", "SubmittedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_attempts_quiz");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("ix_attempts_open")
                        .HasFilter("\"status\" = 'InProgress'");

                    b.ToTable("attempts", (string)null);
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.AttemptAnswer", b =>
                {
                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint")
                        .HasColumnName("question_id");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<decimal?>("PointsAwarded")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("points_awarded");

                    b.Property<long[]>("SelectedOptionIds")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("selected_option_ids");

                    b.Property<string>("TextAnswer")
                        .HasColumnType("text")
                        .HasColumnName("text_answer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AttemptId", "QuestionId")
                        .HasName("pk_attempt_answers");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_attempt_answers_question_id");

                    b.ToTable("attempt_answers", (string)null);
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<long?>("ActorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Data")
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<string>("EntityId")
                        .HasColumnType("text")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("Action", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_logs_action_created_at");

                    b.HasIndex("ActorUserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_logs_actor_user_id_created_at");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.ClassEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<short?>("GradeId")
                        .HasColumnType("smallint")
                        .HasColumnName("grade_id");

                    b.Property<long?>("HomeroomTeacherId")
                        .HasColumnType("bigint")
                        .HasColumnName("homeroom_teacher_id");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long?>("SchoolYearId")
                        .HasColumnType("bigint")
                        .HasColumnName("school_year_id");

                    b.Property<long?>("TeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("team_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_classes");

                    b.HasIndex("GradeId")
                        .HasDatabaseName("ix_classes_grade_id");

                    b.HasIndex("HomeroomTeacherId")
                        .HasDatabaseName("ix_classes_homeroom_teacher_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_classes_team_id");

                    b.HasIndex("SchoolYearId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_classes_school_year_id_name")
                        .HasFilter("\"school_year_id\" IS NOT NULL");

                    b.ToTable("classes", (string)null);
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.ClassTeacher", b =>
                {
                    b.Property<long>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long?>("SubjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("subject_id");

                    b.HasKey("ClassId", "UserId")
                        .HasName("pk_class_teachers");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("ix_class_teachers_subject_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_class_teachers_user_id");

                    b.ToTable("class_teachers", (string)null);
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.ContentReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .HasColumnType("text")
                        .HasColumnName("detail");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("item_id");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_type");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("ReporterIpHash")
                        .HasColumnType("text")
                        .HasColumnName("reporter_ip_hash");

                    b.Property<long?>("ReporterUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("reporter_user_id");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<long?>("ResolvedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("resolved_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_content_reports");

                    b.HasIndex("ReporterUserId")
                        .HasDatabaseName("ix_content_reports_reporter_user_id");

                    b.HasIndex("ResolvedBy")
                        .HasDatabaseName("ix_content_reports_resolved_by");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_content_reports_status_created_at");

                    b.ToTable("content_reports", (string)null);
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.Document", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AllowGuestDownload")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_guest_download");

                    b.Property<long?>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<long?>("CoverFileId")
                        .HasColumnType("bigint")
                        .HasColumnName("cover_file_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DescriptionHtml")
                        .HasColumnType("text")
                        .HasColumnName("description_html");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("integer")
                        .HasColumnName("download_count");

                    b.Property<short?>("GradeId")
                        .HasColumnType("smallint")
                        .HasColumnName("grade_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean")
                        .HasColumnName("is_featured");

                    b.Property<string>("ModerationNote")
                        .HasColumnType("text")
                        .HasColumnName("moderation_note");

                    b.Property<string>("ModerationStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("moderation_status");

                    b.Property<long?>("OwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset?>("PublishFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publish_from");

                    b.Property<string>("PublishMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("publish_mode");

                    b.Property<DateTimeOffset?>("PublishUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publish_until");

                    b.Property<long?>("SchoolYearId")
                        .HasColumnType("bigint")
                        .HasColumnName("school_year_id");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<string>("SearchText")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("search_text")
                        .HasComputedColumnSql("f_unaccent(lower(coalesce(\"title\",'') || ' ' || coalesce(\"summary\",'')))", true);

                    b.Property<long?>("SectionId")
                        .HasColumnType("bigint")
                        .HasColumnName("section_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<long?>("SubjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("subject_id");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<long?>("TeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("team_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer")
                        .HasColumnName("view_count");

                    b.Property<short?>("WeekNo")
                        .HasColumnType("smallint")
                        .HasColumnName("week_no");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_documents_class_id");

                    b.HasIndex("CoverFileId")
                        .HasDatabaseName("ix_documents_cover_file_id");

                    b.HasIndex("GradeId")
                        .HasDatabaseName("ix_documents_grade_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_documents_owner_id");

                    b.HasIndex("SchoolYearId")
                        .HasDatabaseName("ix_documents_school_year_id");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("ix_documents_subject_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_documents_team_id");

                    b.HasIndex("SectionId", "GradeId")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_docs_browse_live")
                        .HasFilter("NOT \"is_deleted\"");

                    b.HasIndex("PublishMode", "PublishFrom", "PublishUntil")
                        .HasDatabaseName("ix_documents_publish_mode_publish_from_publish_until");

                    b.HasIndex("SectionId", "GradeId", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_docs_browse");

                    b.ToTable("documents", null, t =>
                        {
                            t.HasCheckConstraint("ck_documents_week", "week_no IS NULL OR (week_no >= 1 AND week_no <= 37)");
                        });
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.DocumentFile", b =>
                {
                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("document_id");

                    b.Property<long>("FileId")
                        .HasColumnType("bigint")
                        .HasColumnName("file_id");

                    b.Property<short>("Sort")
                        .HasColumnType("smallint")
                        .HasColumnName("sort");

                    b.HasKey("DocumentId", "FileId")
                        .HasName("pk_document_files");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_document_files_file_id");

                    b.ToTable("document_files", (string)null);
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.DocumentTag", b =>
                {
                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("document_id");

                    b.Property<long>("TagId")
                        .HasColumnType("bigint")
                        .HasColumnName("tag_id");

                    b.HasKey("DocumentId", "TagId")
                        .HasName("pk_document_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_document_tags_tag_id");

                    b.ToTable("document_tags", (string)null);
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.Favorite", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("ItemType")
                        .HasColumnType("text")
                        .HasColumnName("item_type");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("item_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("UserId", "ItemType", "ItemId")
                        .HasName("pk_favorites");

                    b.ToTable("favorites", (string)null);
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.FileEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Bytes")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Ext")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ext");

                    b.Property<string>("Mime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mime");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_name");

                    b.Property<long?>("OwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_id");

                    b.Property<int?>("PreviewPages")
                        .HasColumnType("integer")
                        .HasColumnName("preview_pages");

                    b.Property<string>("PreviewPublicId")
                        .HasColumnType("text")
                        .HasColumnName("preview_public_id");

                    b.Property<short>("ProcessingAttempts")
                        .HasColumnType("smallint")
                        .HasColumnName("processing_attempts");

                    b.Property<string>("ProcessingError")
                        .HasColumnType("text")
                        .HasColumnName("processing_error");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("processing_status");

                    b.Property<long?>("QuizId")
                        .HasColumnType("bigint")
                        .HasColumnName("quiz_id");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sha256");

                    b.Property<string>("StoragePublicId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_public_id");

                    b.Property<string>("StorageResourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_resource_type");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url");

                    b.HasKey("Id")
                        .HasName("pk_files");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_files_owner_id");

                    b.HasIndex("QuizId")
                        .HasDatabaseName("ix_files_quiz_id");

                    b.HasIndex("StoragePublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_files_storage_public_id");

                    b.ToTable("files", (string)null);
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.Grade", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<short>("Sort")
                        .HasColumnType("smallint")
                        .HasColumnName("sort");

                    b.HasKey("Id")
                        .HasName("pk_grades");

                    b.ToTable("grades", (string)null);
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<long?>("AcceptedUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("accepted_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<long?>("InvitedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("invited_by");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("team_id");

                    b.Property<string>("TeamRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("team_role");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<string>("TokenText")
                        .HasColumnType("text")
                        .HasColumnName("token_text");

                    b.HasKey("Id")
                        .HasName("pk_invitations");

                    b.HasIndex("AcceptedUserId")
                        .HasDatabaseName("ix_invitations_accepted_user_id");

                    b.HasIndex("InvitedBy")
                        .HasDatabaseName("ix_invitations_invited_by");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_invitations_team_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_invitations_token_hash");

                    b.HasIndex("Email", "TeamId")
                        .IsUnique()
                        .HasDatabaseName("ux_invite_open")
                        .HasFilter("\"accepted_at\" IS NULL AND \"revoked_at\" IS NULL");

                    b.ToTable("invitations", (string)null);
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Link")
                        .HasColumnType("text")
                        .HasColumnName("link");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId", "ReadAt")
                        .HasDatabaseName("ix_notifications_user_id_read_at");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.Question", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string[]>("AcceptedAnswers")
                        .HasColumnType("text[]")
                        .HasColumnName("accepted_answers");

                    b.Property<string>("ContentHtml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_html");

                    b.Property<string>("ExplanationHtml")
                        .HasColumnType("text")
                        .HasColumnName("explanation_html");

                    b.Property<long?>("GroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("group_id");

                    b.Property<decimal>("Points")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("points");

                    b.Property<long>("QuizId")
                        .HasColumnType("bigint")
                        .HasColumnName("quiz_id");

                    b.Property<short>("Sort")
                        .HasColumnType("smallint")
                        .HasColumnName("sort");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_questions_group_id");

                    b.HasIndex("QuizId")
                        .HasDatabaseName("ix_questions_quiz_id");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.QuestionGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("PassageHtml")
                        .HasColumnType("text")
                        .HasColumnName("passage_html");

                    b.Property<long>("QuizId")
                        .HasColumnType("bigint")
                        .HasColumnName("quiz_id");

                    b.Property<short>("Sort")
                        .HasColumnType("smallint")
                        .HasColumnName("sort");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_question_groups");

                    b.HasIndex("QuizId")
                        .HasDatabaseName("ix_question_groups_quiz_id");

                    b.ToTable("question_groups", (string)null);
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.QuestionOption", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentHtml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_html");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint")
                        .HasColumnName("question_id");

                    b.Property<short>("Sort")
                        .HasColumnType("smallint")
                        .HasColumnName("sort");

                    b.HasKey("Id")
                        .HasName("pk_question_options");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_question_options_question_id");

                    b.ToTable("question_options", (string)null);
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.Quiz", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DescriptionHtml")
                        .HasColumnType("text")
                        .HasColumnName("description_html");

                    b.Property<short?>("GradeId")
                        .HasColumnType("smallint")
                        .HasColumnName("grade_id");

                    b.Property<string>("IdentityMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identity_mode");

                    b.Property<string>("ImportWarnings")
                        .HasColumnType("jsonb")
                        .HasColumnName("import_warnings");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean")
                        .HasColumnName("is_featured");

                    b.Property<short?>("MaxAttempts")
                        .HasColumnType("smallint")
                        .HasColumnName("max_attempts");

                    b.Property<string>("ModerationStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("moderation_status");

                    b.Property<string>("MultiScoring")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("multi_scoring");

                    b.Property<long?>("OwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_id");

                    b.Property<long?>("PrintFileId")
                        .HasColumnType("bigint")
                        .HasColumnName("print_file_id");

                    b.Property<DateTimeOffset?>("PublishFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publish_from");

                    b.Property<string>("PublishMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("publish_mode");

                    b.Property<DateTimeOffset?>("PublishUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publish_until");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("integer")
                        .HasColumnName("question_count");

                    b.Property<long?>("SchoolYearId")
                        .HasColumnType("bigint")
                        .HasColumnName("school_year_id");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<string>("ScoreRounding")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("score_rounding");

                    b.Property<string>("SearchText")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("search_text")
                        .HasComputedColumnSql("f_unaccent(lower(regexp_replace(coalesce(\"title\",'') || ' ' || coalesce(\"description_html\",''), '<[^>]+>', ' ', 'g')))", true);

                    b.Property<long?>("SectionId")
                        .HasColumnType("bigint")
                        .HasColumnName("section_id");

                    b.Property<string>("ShowAnswers")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("show_answers");

                    b.Property<bool>("ShuffleOptions")
                        .HasColumnType("boolean")
                        .HasColumnName("shuffle_options");

                    b.Property<bool>("ShuffleQuestions")
                        .HasColumnType("boolean")
                        .HasColumnName("shuffle_questions");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<long?>("SourceFileId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_file_id");

                    b.Property<long?>("SubjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("subject_id");

                    b.Property<long?>("TeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("team_id");

                    b.Property<short?>("TimeLimitMinutes")
                        .HasColumnType("smallint")
                        .HasColumnName("time_limit_minutes");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<decimal>("TotalPoints")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("total_points");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<short?>("WeekNo")
                        .HasColumnType("smallint")
                        .HasColumnName("week_no");

                    b.HasKey("Id")
                        .HasName("pk_quizzes");

                    b.HasIndex("GradeId")
                        .HasDatabaseName("ix_quizzes_grade_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_quizzes_owner_id");

                    b.HasIndex("PrintFileId")
                        .HasDatabaseName("ix_quizzes_print_file_id");

                    b.HasIndex("SchoolYearId")
                        .HasDatabaseName("ix_quizzes_school_year_id");

                    b.HasIndex("SourceFileId")
                        .HasDatabaseName("ix_quizzes_source_file_id");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("ix_quizzes_subject_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_quizzes_team_id");

                    b.HasIndex("SectionId", "GradeId")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_quizzes_browse_live")
                        .HasFilter("NOT \"is_deleted\"");

                    b.HasIndex("WeekNo", "GradeId")
                        .HasDatabaseName("ix_quizzes_week_no_grade_id")
                        .HasFilter("\"week_no\" IS NOT NULL");

                    b.HasIndex("PublishMode", "PublishFrom", "PublishUntil")
                        .HasDatabaseName("ix_quizzes_publish_mode_publish_from_publish_until");

                    b.HasIndex("SectionId", "GradeId", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_quizzes_browse");

                    b.ToTable("quizzes", null, t =>
                        {
                            t.HasCheckConstraint("ck_quizzes_week", "week_no IS NULL OR (week_no >= 1 AND week_no <= 37)");
                        });
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.SchoolYear", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_school_years");

                    b.HasIndex("IsCurrent")
                        .IsUnique()
                        .HasDatabaseName("ux_one_current_year")
                        .HasFilter("\"is_current\" = TRUE");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_school_years_name");

                    b.ToTable("school_years", (string)null);
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.Section", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<string>("ContentKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_kind");

                    b.Property<string>("DefaultPublishMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_publish_mode");

                    b.Property<string>("DefaultScope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_scope");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_internal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("RequireWeek")
                        .HasColumnType("boolean")
                        .HasColumnName("require_week");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<short>("Sort")
                        .HasColumnType("smallint")
                        .HasColumnName("sort");

                    b.HasKey("Id")
                        .HasName("pk_sections");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_sections_slug");

                    b.ToTable("sections", (string)null);
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.StaticPage", b =>
                {
                    b.Property<string>("Slug")
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("BodyMarkdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_markdown");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.HasKey("Slug")
                        .HasName("pk_static_pages");

                    b.ToTable("static_pages", (string)null);
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.Student", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<short?>("Ordinal")
                        .HasColumnType("smallint")
                        .HasColumnName("ordinal");

                    b.Property<string>("StudentCode")
                        .HasColumnType("text")
                        .HasColumnName("student_code");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_students");

                    b.HasIndex("ClassId", "FullName")
                        .HasDatabaseName("ix_students_class_id_full_name");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.Subject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<short>("Sort")
                        .HasColumnType("smallint")
                        .HasColumnName("sort");

                    b.HasKey("Id")
                        .HasName("pk_subjects");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_subjects_slug");

                    b.ToTable("subjects", (string)null);
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_slug");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.Team", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<short?>("GradeId")
                        .HasColumnType("smallint")
                        .HasColumnName("grade_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("GradeId")
                        .HasDatabaseName("ix_teams_grade_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_teams_name");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.TeamMember", b =>
                {
                    b.Property<long>("TeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("team_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("TeamId", "UserId")
                        .HasName("pk_team_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_team_members_user_id");

                    b.HasIndex("TeamId", "Role")
                        .IsUnique()
                        .HasDatabaseName("ux_team_one_lead")
                        .HasFilter("\"role\" = 'Lead'");

                    b.ToTable("team_members", (string)null);
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<long?>("ApprovedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("approved_by");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("GoogleSub")
                        .HasColumnType("text")
                        .HasColumnName("google_sub");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<long?>("RequestedTeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("requested_team_id");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("uuid")
                        .HasColumnName("security_stamp");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<string>("StatusReason")
                        .HasColumnType("text")
                        .HasColumnName("status_reason");

                    b.Property<string>("SystemRole")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Teacher")
                        .HasColumnName("system_role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("ApprovedBy")
                        .HasDatabaseName("ix_users_approved_by");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("GoogleSub")
                        .IsUnique()
                        .HasDatabaseName("ix_users_google_sub");

                    b.HasIndex("RequestedTeamId")
                        .HasDatabaseName("ix_users_requested_team_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.Announcement", b =>
                {
                    b.HasOne("HocLieu.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_announcements_teams_team_id");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.Assignment", b =>
                {
                    b.HasOne("HocLieu.Domain.Entities.ClassEntity", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignments_classes_class_id");

                    b.HasOne("HocLieu.Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignments_users_created_by");

                    b.HasOne("HocLieu.Domain.Entities.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignments_quizzes_quiz_id");

                    b.Navigation("Class");

                    b.Navigation("Creator");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.Attempt", b =>
                {
                    b.HasOne("HocLieu.Domain.Entities.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_attempts_assignments_assignment_id");

                    b.HasOne("HocLieu.Domain.Entities.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attempts_quizzes_quiz_id");

                    b.HasOne("HocLieu.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_attempts_students_student_id");

                    b.Navigation("Assignment");

                    b.Navigation("Quiz");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.AttemptAnswer", b =>
                {
                    b.HasOne("HocLieu.Domain.Entities.Attempt", "Attempt")
                        .WithMany("Answers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attempt_answers_attempts_attempt_id");

                    b.HasOne("HocLieu.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attempt_answers_questions_question_id");

                    b.Navigation("Attempt");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("HocLieu.Domain.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_audit_logs_users_actor_user_id");

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.ClassEntity", b =>
                {
                    b.HasOne("HocLieu.Domain.Entities.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_classes_grades_grade_id");

                    b.HasOne("HocLieu.Domain.Entities.User", "HomeroomTeacher")
                        .WithMany()
                        .HasForeignKey("HomeroomTeacherId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_classes_users_homeroom_teacher_id");

                    b.HasOne("HocLieu.Domain.Entities.SchoolYear", "SchoolYear")
                        .WithMany()
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_classes_school_years_school_year_id");

                    b.HasOne("HocLieu.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_classes_teams_team_id");

                    b.Navigation("Grade");

                    b.Navigation("HomeroomTeacher");

                    b.Navigation("SchoolYear");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.ClassTeacher", b =>
                {
                    b.HasOne("HocLieu.Domain.Entities.ClassEntity", "Class")
                        .WithMany("Teachers")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_class_teachers_classes_class_id");

                    b.HasOne("HocLieu.Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_class_teachers_subjects_subject_id");

                    b.HasOne("HocLieu.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_class_teachers_users_user_id");

                    b.Navigation("Class");

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.ContentReport", b =>
                {
                    b.HasOne("HocLieu.Domain.Entities.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_content_reports_users_reporter_user_id");

                    b.HasOne("HocLieu.Domain.Entities.User", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_content_reports_users_resolved_by");

                    b.Navigation("Reporter");

                    b.Navigation("ResolvedByUser");
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.Document", b =>
                {
                    b.HasOne("HocLieu.Domain.Entities.ClassEntity", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_documents_classes_class_id");

                    b.HasOne("HocLieu.Domain.Entities.FileEntity", "CoverFile")
                        .WithMany()
                        .HasForeignKey("CoverFileId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_documents_files_cover_file_id");

                    b.HasOne("HocLieu.Domain.Entities.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_documents_grades_grade_id");

                    b.HasOne("HocLieu.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_documents_users_owner_id");

                    b.HasOne("HocLieu.Domain.Entities.SchoolYear", "SchoolYear")
                        .WithMany()
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_documents_school_years_school_year_id");

                    b.HasOne("HocLieu.Domain.Entities.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_documents_sections_section_id");

                    b.HasOne("HocLieu.Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_documents_subjects_subject_id");

                    b.HasOne("HocLieu.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_documents_teams_team_id");

                    b.Navigation("Class");

                    b.Navigation("CoverFile");

                    b.Navigation("Grade");

                    b.Navigation("Owner");

                    b.Navigation("SchoolYear");

                    b.Navigation("Section");

                    b.Navigation("Subject");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.DocumentFile", b =>
                {
                    b.HasOne("HocLieu.Domain.Entities.Document", "Document")
                        .WithMany("Files")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_files_documents_document_id");

                    b.HasOne("HocLieu.Domain.Entities.FileEntity", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_files_files_file_id");

                    b.Navigation("Document");

                    b.Navigation("File");
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.DocumentTag", b =>
                {
                    b.HasOne("HocLieu.Domain.Entities.Document", "Document")
                        .WithMany("Tags")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_tags_documents_document_id");

                    b.HasOne("HocLieu.Domain.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_tags_tags_tag_id");

                    b.Navigation("Document");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.Favorite", b =>
                {
                    b.HasOne("HocLieu.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favorites_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.FileEntity", b =>
                {
                    b.HasOne("HocLieu.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_files_users_owner_id");

                    b.HasOne("HocLieu.Domain.Entities.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_files_quizzes_quiz_id");

                    b.Navigation("Owner");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.Invitation", b =>
                {
                    b.HasOne("HocLieu.Domain.Entities.User", "AcceptedUser")
                        .WithMany()
                        .HasForeignKey("AcceptedUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_invitations_users_accepted_user_id");

                    b.HasOne("HocLieu.Domain.Entities.User", "Inviter")
                        .WithMany()
                        .HasForeignKey("InvitedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_invitations_users_invited_by");

                    b.HasOne("HocLieu.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_teams_team_id");

                    b.Navigation("AcceptedUser");

                    b.Navigation("Inviter");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.Notification", b =>
                {
                    b.HasOne("HocLieu.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.Question", b =>
                {
                    b.HasOne("HocLieu.Domain.Entities.QuestionGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_questions_question_groups_group_id");

                    b.HasOne("HocLieu.Domain.Entities.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questions_quizzes_quiz_id");

                    b.Navigation("Group");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.QuestionGroup", b =>
                {
                    b.HasOne("HocLieu.Domain.Entities.Quiz", "Quiz")
                        .WithMany("Groups")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_groups_quizzes_quiz_id");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.QuestionOption", b =>
                {
                    b.HasOne("HocLieu.Domain.Entities.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_options_questions_question_id");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.Quiz", b =>
                {
                    b.HasOne("HocLieu.Domain.Entities.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_quizzes_grades_grade_id");

                    b.HasOne("HocLieu.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_quizzes_users_owner_id");

                    b.HasOne("HocLieu.Domain.Entities.FileEntity", "PrintFile")
                        .WithMany()
                        .HasForeignKey("PrintFileId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_quizzes_files_print_file_id");

                    b.HasOne("HocLieu.Domain.Entities.SchoolYear", "SchoolYear")
                        .WithMany()
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_quizzes_school_years_school_year_id");

                    b.HasOne("HocLieu.Domain.Entities.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_quizzes_sections_section_id");

                    b.HasOne("HocLieu.Domain.Entities.FileEntity", "SourceFile")
                        .WithMany()
                        .HasForeignKey("SourceFileId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_quizzes_files_source_file_id");

                    b.HasOne("HocLieu.Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_quizzes_subjects_subject_id");

                    b.HasOne("HocLieu.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_quizzes_teams_team_id");

                    b.Navigation("Grade");

                    b.Navigation("Owner");

                    b.Navigation("PrintFile");

                    b.Navigation("SchoolYear");

                    b.Navigation("Section");

                    b.Navigation("SourceFile");

                    b.Navigation("Subject");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.Student", b =>
                {
                    b.HasOne("HocLieu.Domain.Entities.ClassEntity", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_students_classes_class_id");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.Team", b =>
                {
                    b.HasOne("HocLieu.Domain.Entities.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_teams_grades_grade_id");

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.TeamMember", b =>
                {
                    b.HasOne("HocLieu.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_members_teams_team_id");

                    b.HasOne("HocLieu.Domain.Entities.User", "User")
                        .WithMany("TeamMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_members_users_user_id");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.User", b =>
                {
                    b.HasOne("HocLieu.Domain.Entities.User", "Approver")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_users_users_approved_by");

                    b.HasOne("HocLieu.Domain.Entities.Team", "RequestedTeam")
                        .WithMany()
                        .HasForeignKey("RequestedTeamId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_users_teams_requested_team_id");

                    b.Navigation("Approver");

                    b.Navigation("RequestedTeam");
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.Attempt", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.ClassEntity", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.Document", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.Question", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.Quiz", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("HocLieu.Domain.Entities.User", b =>
                {
                    b.Navigation("TeamMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
